<a href="https://colab.research.google.com/github/gabrielhenrique1978-del/Python-e-ia-aplicada/blob/main/Desafio_analise_de_sentimento.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Análise de Sentimento de Avaliações de Produtos com Groq API

Este notebook demonstra como realizar análise de sentimento em avaliações de produtos utilizando a API da Groq para processamento de linguagem natural. O objetivo é classificar cada avaliação como 'positiva', 'negativa' ou 'neutra' e adicionar essa classificação ao DataFrame original.

## Etapa 1: Carregamento dos Dados

In [ ]:
import pandas as pd
# etapa 1
df_reviews = pd.read_csv('/content/reviews (1).csv')

Primeiro, importamos a biblioteca `pandas` para manipulação de dados e carregamos o arquivo CSV `reviews (1).csv` em um DataFrame chamado `df_reviews`. Este DataFrame contém as avaliações dos produtos.

In [ ]:
df_reviews

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0
5,A2Q3ICGWZLY3JJ,B007WTAJTO,98020,"It works, but file writes are a bit slower tha...",1384905600,20/11/2013,383,0,0
6,AF24M1HKIZ7QC,B007WTAJTO,"Abdulrahman J. Alrashed ""dr34m3r""","I bought 2 of those SanDisk 32 GB microSD , us...",1375488000,08/03/2013,640,0,0
7,A1KIF9Z5VFPH7H,B007WTAJTO,"Abel Feliciano ""Ace Master""",The memory card is an excellent condition and ...,1347321600,09/11/2012,759,0,0
8,A1FKE13D77L3Y3,B007WTAJTO,Abraham Arturo Meza Marin,I bougth this micro SD card after some trubles...,1361232000,19/02/2013,657,0,0
9,A1X1FX3NSOFCT3,B007WTAJTO,"Abused Commuter ""abused_commuter""",Ordered this for a Galaxy S3. Lasted a few mo...,1374278400,20/07/2013,506,0,1
10,A3RV1L35IPTV61,B007WTAJTO,abushaheed,more like 8mb/s in my Note 10.1 and that's usi...,1357430400,01/06/2013,555,0,0
11,A2RJ7DAL63MN1F,B007WTAJTO,Ace of Sevens,"I used this for a few months in my phone, then...",1391126400,31/01/2014,311,0,0
12,A3IJIFZ5HH819V,B007WTAJTO,A. Cho,"everything about it was great, except for the ...",1373414400,07/10/2013,427,0,0
13,A1R0JMNRV7HVQM,B007WTAJTO,ACZ,Used in my phone it's plenty fast and works ju...,1383609600,11/05/2013,576,0,0
14,APAEBFIM1588A,B007WTAJTO,"Adam Wright ""Electrical Engineer""",This card advertises itself as UHS1 but it's a...,1378684800,09/09/2013,455,1,1
15,A1JOXGZH55JMHW,B007WTAJTO,A. Hejazi,I bought this SD card for my android phone thi...,1386806400,12/12/2013,361,0,0
16,A35NR2GQWMQ31K,B007WTAJTO,ahhsimon,good card. work as describes. haven't had any ...,1391644800,02/06/2014,189,0,0
17,A1N7LGUPJWWQS9,B007WTAJTO,A.J. Matheson,I got this because I just couldn't pass up the...,1353888000,26/11/2012,742,0,0
18,A28CTDM7OP0RAR,B007WTAJTO,Alan,It works but the actual R/W speeds are 18/8 MB...,1395705600,25/03/2014,258,0,0
19,A1NA2JGI3GNDN2,B007WTAJTO,Albert,Does it's job and fairly cheap for what it's w...,1399161600,05/04/2014,247,0,0
20,A3PCW69GQK8R38,B007WTAJTO,Alejandro Hernndez,Still don't feel is very fast or is just my ph...,1391385600,02/03/2014,281,0,0
21,A1UM44ILLZCEI1,B007WTAJTO,Aleksandar Milivojevic,I bought 64GB version of the card to use with ...,1364947200,04/03/2013,644,1,1
22,A2T71JNR3C2DY1,B007WTAJTO,"Ali Etezadkhah ""Ali""",I have an old SanDisk SD card that still works...,1371859200,22/06/2013,534,0,0
23,A87U7LY9OKZNY,B007WTAJTO,A. Liu,Used it in my Galaxy Note 2 for the past 16 mo...,1398988800,05/02/2014,306,0,0
24,A277QWS5WF6DWI,B007WTAJTO,Alton L Spencer,Worked great in my galaxy s4--until it didn't ...,1401148800,27/05/2014,195,0,0
25,A1WWPAQ1DD6BQC,B007WTAJTO,A. Marte,I bought this on August of 2013. As of April ...,1403654400,25/06/2014,166,1,1
26,A3FY6V3LXP8SSL,B007WTAJTO,"Amazon Customer ""fiction buff""",So this product is a large disappointment...bo...,1349136000,10/02/2012,1032,0,0
27,A3DXCQV1U6QLTS,B007WTAJTO,Amazon Customer,I will keep it short and sweet for potential b...,1360195200,02/07/2013,524,0,0
28,A3R2TY7PFN9VSM,B007WTAJTO,Amazon Customer,"The package arrived on time, it's very well pa...",1375660800,08/05/2013,579,0,0
29,A1FZKP9XTKMALD,B007WTAJTO,Amazon Customer,"Does what it says. Hasn't broken yet, and I ho...",1375401600,08/02/2013,668,0,1
30,A308JP3BK4VAL7,B007WTAJTO,Amazon Customer,Thus microSD card worked fine for a year in my...,1398643200,28/04/2014,224,0,3
31,A392ZR68AKLDCK,B007WTAJTO,"Amazon Customer ""Music Fan""","I think this is probably a fine product, but i...",1374796800,26/07/2013,500,1,1
32,A2DQ2U5BYIXNUJ,B007WTAJTO,"Amazon Customer ""PawsitivelySafe""",I have two of these and use them for my Galazy...,1387152000,16/12/2013,357,0,0
33,A14D2PS27PI3FM,B007WTAJTO,Amazon Fan,I join the long list of customers who have had...,1359936000,02/04/2013,615,1,2
34,A1Z7FZP81N8CDU,B007WTAJTO,Amazon Shopper,"I do not get the advertised speed of 30MB/s, m...",1394755200,14/03/2014,269,0,1
35,A1T8FVB93QQNOM,B007WTAJTO,Andrew M. Swiatek,the micro sd works great as described. but bew...,1372464000,29/06/2013,527,0,0
36,A3K1JZPUXSADRJ,B007WTAJTO,anonomous,than i expected. I don't know if it would kill...,1362182400,03/02/2013,673,0,2
37,A1D07XDTMWV0A5,B007WTAJTO,"A. Shieh ""eff.org""","Reliable and inexpensive. However, it's quite ...",1385769600,30/11/2013,373,0,0
38,A1HKW2TELCHGLL,B007WTAJTO,astraelraen,I bought this primarily to use in my Surface P...,1391040000,30/01/2014,312,0,0
39,A3P86Z2D81VLYV,B007WTAJTO,"Zeality ""N2iT""",I really don't know what to think about this I...,1396137600,30/03/2014,253,0,0

Exibimos o DataFrame carregado para ter uma visão geral dos dados, incluindo as colunas disponíveis e as primeiras linhas das avaliações.

In [ ]:
coluna_review = df_reviews['reviewText']
print(coluna_review)

Extraímos a coluna `reviewText` do DataFrame `df_reviews`, que contém o texto das avaliações que serão analisadas. Esta coluna é armazenada em uma variável separada para facilitar o processamento.

In [ ]:
!pip install -q groq

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.7/143.7 kB 3.5 MB/s eta 0:00:00

## Etapa 2: Configuração da Groq API

Instalamos a biblioteca `groq` para interagir com a API da Groq. O `-q` garante uma instalação silenciosa.

In [ ]:
import os
from google.colab import userdata
os.environ['groq_api_key'] = userdata.get('groq_key')

Configuramos a chave da API Groq. É uma boa prática armazenar chaves de API em segredos (secrets) do Colab para evitar expor a chave diretamente no código. Aqui, a chave é carregada do ambiente de usuário (`userdata`).

In [ ]:
import os
from groq import Groq

client = Groq(api_key=os.environ['groq_api_key'])
completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Explain the importance of low-latency LLMs",
        }
    ],
    model="openai/gpt-oss-20b"
)

Inicializamos o cliente Groq com a chave da API e fazemos uma chamada de exemplo para garantir que a API está funcionando corretamente. Isso verifica a conectividade e a autenticação com a Groq API.

In [ ]:
lista_de_analise_sentimentos =[]

for review_numero, resenha in enumerate(coluna_review):
  resposta = client.chat.completions.create(
      model="openai/gpt-oss-20b",
      messages=[
          {
              "role": "user",
              "content": f'''voce ira analisar a resenha que eu te mandarei abaixo, e retornara com uma analise de sentimento. voce deve responder com uma das seguintes palavras: ''positiva'', ''negativa'' ou ''neutra'', indicando o sentimento relativo a resenha especifica.\n\n              Resenha: {resenha}'''
          }
      ]
  )

  lista_de_analise_sentimentos.append(resposta.choices[0].message.content)

## Etapa 3: Análise de Sentimento

Iteramos sobre cada resenha na `coluna_review`, enviando o texto da resenha para a Groq API para análise de sentimento. A API é instruída a retornar o sentimento como 'positiva', 'negativa' ou 'neutra'. Os resultados são armazenados em `lista_de_analise_sentimentos`.

In [ ]:
lista_de_analise_sentimentos

['neutra',
 'positiva',
 'positiva',
 'positiva',
 'positiva',
 'positiva',
 'negativa',
 'positiva',
 'negativa',
 'negativa',
 'negativa',
 'negativa',
 'positiva',
 'positiva',
 'negativa',
 'negativa',
 'positiva',
 'positiva',
 'negativa',
 'neutra',
 'neutra',
 'negativa',
 'negativa',
 'negativa',
 'negativa',
 'negativa',
 'negativa',
 'negativa',
 'neutra',
 'positiva',
 'negativa',
 'negativa',
 'positiva',
 'neutra',
 'negativa',
 'negativa',
 'negativa',
 'negativa',
 'negativa',
 'negativa']

Exibimos a lista completa de análises de sentimento que foram geradas pela Groq API.

In [ ]:
df_reviews['analises de sentimentos'] = lista_de_analise_sentimentos

## Etapa 4: Integração dos Resultados

Adicionamos a `lista_de_analise_sentimentos` como uma nova coluna chamada `'analises de sentimentos'` ao DataFrame original `df_reviews`. Isso integra os resultados da análise de sentimento diretamente com os dados das avaliações.

In [ ]:
df_reviews

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote,analises de sentimentos
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0,neutra
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0,positiva
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0,positiva
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0,positiva
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0,positiva
5,A2Q3ICGWZLY3JJ,B007WTAJTO,98020,"It works, but file writes are a bit slower tha...",1384905600,20/11/2013,383,0,0,positiva
6,AF24M1HKIZ7QC,B007WTAJTO,"Abdulrahman J. Alrashed ""dr34m3r""","I bought 2 of those SanDisk 32 GB microSD , us...",1375488000,08/03/2013,640,0,0,negativa
7,A1KIF9Z5VFPH7H,B007WTAJTO,"Abel Feliciano ""Ace Master""",The memory card is an excellent condition and ...,1347321600,09/11/2012,759,0,0,positiva
8,A1FKE13D77L3Y3,B007WTAJTO,Abraham Arturo Meza Marin,I bougth this micro SD card after some trubles...,1361232000,19/02/2013,657,0,0,negativa
9,A1X1FX3NSOFCT3,B007WTAJTO,"Abused Commuter ""abused_commuter""",Ordered this for a Galaxy S3. Lasted a few mo...,1374278400,20/07/2013,506,0,1,negativa
10,A3RV1L35IPTV61,B007WTAJTO,abushaheed,more like 8mb/s in my Note 10.1 and that's usi...,1357430400,01/06/2013,555,0,0,negativa
11,A2RJ7DAL63MN1F,B007WTAJTO,Ace of Sevens,"I used this for a few months in my phone, then...",1391126400,31/01/2014,311,0,0,negativa
12,A3IJIFZ5HH819V,B007WTAJTO,A. Cho,"everything about it was great, except for the ...",1373414400,07/10/2013,427,0,0,positiva
13,A1R0JMNRV7HVQM,B007WTAJTO,ACZ,Used in my phone it's plenty fast and works ju...,1383609600,11/05/2013,576,0,0,positiva
14,APAEBFIM1588A,B007WTAJTO,"Adam Wright ""Electrical Engineer""",This card advertises itself as UHS1 but it's a...,1378684800,09/09/2013,455,1,1,negativa
15,A1JOXGZH55JMHW,B007WTAJTO,A. Hejazi,I bought this SD card for my android phone thi...,1386806400,12/12/2013,361,0,0,negativa
16,A35NR2GQWMQ31K,B007WTAJTO,ahhsimon,good card. work as describes. haven't had any ...,1391644800,02/06/2014,189,0,0,positiva
17,A1N7LGUPJWWQS9,B007WTAJTO,A.J. Matheson,I got this because I just couldn't pass up the...,1353888000,26/11/2012,742,0,0,positiva
18,A28CTDM7OP0RAR,B007WTAJTO,Alan,It works but the actual R/W speeds are 18/8 MB...,1395705600,25/03/2014,258,0,0,negativa
19,A1NA2JGI3GNDN2,B007WTAJTO,Albert,Does it's job and fairly cheap for what it's w...,1399161600,05/04/2014,247,0,0,neutra
20,A3PCW69GQK8R38,B007WTAJTO,Alejandro Hernndez,Still don't feel is very fast or is just my ph...,1391385600,02/03/2014,281,0,0,neutra
21,A1UM44ILLZCEI1,B007WTAJTO,Aleksandar Milivojevic,I bought 64GB version of the card to use with ...,1364947200,04/03/2013,644,1,1,negativa
22,A2T71JNR3C2DY1,B007WTAJTO,"Ali Etezadkhah ""Ali""",I have an old SanDisk SD card that still works...,1371859200,22/06/2013,534,0,0,negativa
23,A87U7LY9OKZNY,B007WTAJTO,A. Liu,Used it in my Galaxy Note 2 for the past 16 mo...,1398988800,05/02/2014,306,0,0,negativa
24,A277QWS5WF6DWI,B007WTAJTO,Alton L Spencer,Worked great in my galaxy s4--until it didn't ...,1401148800,27/05/2014,195,0,0,negativa
25,A1WWPAQ1DD6BQC,B007WTAJTO,A. Marte,I bought this on August of 2013. As of April ...,1403654400,25/06/2014,166,1,1,negativa
26,A3FY6V3LXP8SSL,B007WTAJTO,"Amazon Customer ""fiction buff""",So this product is a large disappointment...bo...,1349136000,10/02/2012,1032,0,0,negativa
27,A3DXCQV1U6QLTS,B007WTAJTO,Amazon Customer,I will keep it short and sweet for potential b...,1360195200,02/07/2013,524,0,0,negativa
28,A3R2TY7PFN9VSM,B007WTAJTO,Amazon Customer,"The package arrived on time, it's very well pa...",1375660800,08/05/2013,579,0,0,neutra
29,A1FZKP9XTKMALD,B007WTAJTO,Amazon Customer,"Does what it says. Hasn't broken yet, and I ho...",1375401600,08/02/2013,668,0,1,positiva
30,A308JP3BK4VAL7,B007WTAJTO,Amazon Customer,Thus microSD card worked fine for a year in my...,1398643200,28/04/2014,224,0,3,negativa
31,A392ZR68AKLDCK,B007WTAJTO,"Amazon Customer ""Music Fan""","I think this is probably a fine product, but i...",1374796800,26/07/2013,500,1,1,negativa
32,A2DQ2U5BYIXNUJ,B007WTAJTO,"Amazon Customer ""PawsitivelySafe""",I have two of these and use them for my Galazy...,1387152000,16/12/2013,357,0,0,positiva
33,A14D2PS27PI3FM,B007WTAJTO,Amazon Fan,I join the long list of customers who have had...,1359936000,02/04/2013,615,1,2,neutra
34,A1Z7FZP81N8CDU,B007WTAJTO,Amazon Shopper,"I do not get the advertised speed of 30MB/s, m...",1394755200,14/03/2014,269,0,1,negativa
35,A1T8FVB93QQNOM,B007WTAJTO,Andrew M. Swiatek,the micro sd works great as described. but bew...,1372464000,29/06/2013,527,0,0,negativa
36,A3K1JZPUXSADRJ,B007WTAJTO,anonomous,than i expected. I don't know if it would kill...,1362182400,03/02/2013,673,0,2,negativa
37,A1D07XDTMWV0A5,B007WTAJTO,"A. Shieh ""eff.org""","Reliable and inexpensive. However, it's quite ...",1385769600,30/11/2013,373,0,0,negativa
38,A1HKW2TELCHGLL,B007WTAJTO,astraelraen,I bought this primarily to use in my Surface P...,1391040000,30/01/2014,312,0,0,negativa
39,A3P86Z2D81VLYV,B007WTAJTO,"Zeality ""N2iT""",I really don't know what to think about this I...,1396137600,30/03/2014,253,0,0,negativa

Por fim, exibimos o DataFrame `df_reviews` atualizado, que agora inclui a nova coluna com as classificações de sentimento para cada avaliação.